CREATE TABLE streams2 (
    stream_id text PRIMARY KEY,
    locked boolean DEFAULT false
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX streams2_pkey ON streams2(stream_id text_ops);



CREATE TABLE events2 (
    id uuid PRIMARY KEY,
    stream_id text NOT NULL,
    type text NOT NULL,
    created_at timestamp without time zone NOT NULL,
    producer text,
    causation_id uuid,
    correlation_id uuid,
    payload jsonb,
    global_seq bigint DEFAULT nextval('events_global_seq'::regclass)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX events2_pkey ON events2(id uuid_ops);
CREATE INDEX events2_stream_id_index ON events2(stream_id text_ops);
CREATE INDEX events2_causation_id_index ON events2(causation_id uuid_ops);


CREATE TABLE commands2 (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_id text NOT NULL REFERENCES streams2(stream_id),
    data jsonb NOT NULL,
    scheduled_at timestamp without time zone NOT NULL DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX commands2_pkey ON commands2(id int4_ops);
