# frozen_string_literal: true

require 'sourced/topology'

module Sourced
  module CCC
    # Analyzes registered CCC reactors (Deciders and Projectors) and builds a
    # flat array of node structs describing the message flow graph. This enables
    # visualization, introspection, and Event Modeling diagram generation for
    # CCC-based systems.
    #
    # Works like {Sourced::Topology} but adapted for CCC's stream-less messages,
    # CCC-specific handler prefixes (+ccc_decide+, +ccc_reaction+), and
    # {CCC::Message} registry.
    #
    # @example Build topology from registered reactors
    #   nodes = Sourced::CCC::Topology.build([MyDecider, MyProjector])
    #   nodes.each do |node|
    #     puts "#{node.type}: #{node.name} (#{node.id})"
    #   end
    #
    # @example Access topology via the CCC module (uses global router)
    #   Sourced::CCC.register(MyDecider)
    #   Sourced::CCC.register(MyProjector)
    #   Sourced::CCC.topology.each { |node| puts node.id }
    #
    # @example Filter by node type
    #   commands = Sourced::CCC::Topology.build(reactors).select { |n| n.type == 'command' }
    #   commands.each { |cmd| puts "#{cmd.name} => #{cmd.produces.inspect}" }
    #
    # @see Sourced::Topology
    module Topology
      # @!parse
      #   # A command node in the topology graph.
      #   # @attr type [String] always +'command'+
      #   # @attr id [String] message type string (e.g. +'orders.create_order'+)
      #   # @attr name [String] Ruby class name (e.g. +'Orders::CreateOrder'+)
      #   # @attr group_id [String] reactor group that handles this command
      #   # @attr produces [Array<String>] event type strings produced by this command handler
      #   # @attr schema [Hash] JSON Schema of the command payload, or +{}+
      #   CommandNode = Struct.new(:type, :id, :name, :group_id, :produces, :schema)
      #
      #   # An event node in the topology graph.
      #   # @attr type [String] always +'event'+
      #   # @attr id [String] message type string
      #   # @attr name [String] Ruby class name
      #   # @attr group_id [String] reactor group where this event was first seen
      #   # @attr produces [Array<String>] always +[]+
      #   # @attr schema [Hash] JSON Schema of the event payload, or +{}+
      #   EventNode = Struct.new(:type, :id, :name, :group_id, :produces, :schema)
      #
      #   # An automation (reaction) node in the topology graph.
      #   # @attr type [String] always +'automation'+
      #   # @attr id [String] composite ID (e.g. +'evt.type-GroupId-aut'+)
      #   # @attr name [String] human-readable label (e.g. +'reaction(WidgetCreated)'+)
      #   # @attr group_id [String] reactor group that owns this reaction
      #   # @attr consumes [Array<String>] event type strings or readmodel IDs consumed
      #   # @attr produces [Array<String>] command type strings dispatched
      #   AutomationNode = Struct.new(:type, :id, :name, :group_id, :consumes, :produces)
      #
      #   # A read model node in the topology graph (projectors only).
      #   # @attr type [String] always +'readmodel'+
      #   # @attr id [String] composite ID (e.g. +'my_app.widget_projector-rm'+)
      #   # @attr name [String] projector group_id
      #   # @attr group_id [String] projector group_id
      #   # @attr consumes [Array<String>] event type strings that feed this read model
      #   # @attr produces [Array<String>] automation node IDs triggered by this read model
      #   # @attr schema [Hash] always +{}+
      #   ReadModelNode = Struct.new(:type, :id, :name, :group_id, :consumes, :produces, :schema)

      CommandNode = Sourced::Topology::CommandNode
      EventNode = Sourced::Topology::EventNode
      AutomationNode = Sourced::Topology::AutomationNode
      ReadModelNode = Sourced::Topology::ReadModelNode

      # Prism-based source analyzer adapted for CCC handler prefixes.
      #
      # Overrides {Sourced::Topology::SourceAnalyzer#events_produced_by} and
      # {Sourced::Topology::SourceAnalyzer#commands_dispatched_by} to use the
      # +ccc_decide+ and +ccc_reaction+ method name prefixes instead of the
      # main Sourced +decide+ and +reaction+ prefixes.
      #
      # @example
      #   analyzer = CCC::Topology::Analyzer.new
      #   refs = analyzer.events_produced_by(MyDecider, CreateWidget)
      #   # => [[:const, "WidgetCreated"]]
      #
      # @see Sourced::Topology::SourceAnalyzer
      class Analyzer < Sourced::Topology::SourceAnalyzer
        # Extract event references from a CCC command handler block.
        #
        # Looks up the handler method generated by +Decider.command(CmdClass)+
        # and uses Prism AST analysis to find +event(...)+ calls within it.
        #
        # @param reactor [Class] a {CCC::Decider} subclass
        # @param cmd_class [Class] a {CCC::Command} subclass handled by the reactor
        # @return [Array<Array>] AST references, e.g. +[[:const, "WidgetCreated"]]+
        #
        # @example
        #   analyzer.events_produced_by(WidgetDecider, CreateWidget)
        #   # => [[:const, "WidgetCreated"]]
        def events_produced_by(reactor, cmd_class)
          return [] unless @prism_available

          method_name = Sourced.message_method_name('ccc_decide', cmd_class.name)
          extract_calls_from_handler(reactor, method_name, :event)
        end

        # Extract dispatch references from a CCC reaction handler block.
        #
        # Looks up the handler method generated by +reaction(EvtClass)+
        # and uses Prism AST analysis to find +dispatch(...)+ calls within it.
        # Follows chained calls like +dispatch(Cmd).at(time)+.
        #
        # @param reactor [Class] a CCC reactor class (Decider or Projector subclass)
        # @param evt_class [Class] the event class whose reaction handler to analyze
        # @return [Array<Array>] AST references, e.g. +[[:const, "NotifyWidget"]]+
        #
        # @example
        #   analyzer.commands_dispatched_by(WidgetDecider, WidgetCreated)
        #   # => [[:const, "NotifyWidget"]]
        def commands_dispatched_by(reactor, evt_class)
          return [] unless @prism_available

          method_name = Sourced.message_method_name(CCC::React::PREFIX, evt_class.name)
          extract_calls_from_handler(reactor, method_name, :dispatch)
        end
      end

      # Analyze registered CCC reactors and build the topology graph.
      #
      # Iterates each reactor class and extracts:
      # - {CommandNode}s from Decider +handled_commands+, with Prism-extracted +produces+
      # - {EventNode}s from command produces and evolve handlers, deduplicated by type string
      # - {AutomationNode}s from specific and catch-all reactions, with Prism-extracted +produces+
      # - {ReadModelNode}s for Projector subclasses, linking consumed events to automation outputs
      #
      # Nodes are deduplicated across reactors: the first reactor to declare a command or
      # event "owns" it (gets its +group_id+).
      #
      # @param reactors [Enumerable<Class>] reactor classes ({CCC::Decider} and/or
      #   {CCC::Projector} subclasses)
      # @return [Array<CommandNode, EventNode, AutomationNode, ReadModelNode>]
      #   flat array of topology nodes
      #
      # @example Build from explicit reactor list
      #   nodes = CCC::Topology.build([OrderDecider, OrderProjector])
      #
      #   nodes.select { |n| n.type == 'command' }.each do |cmd|
      #     puts "#{cmd.name} produces: #{cmd.produces}"
      #   end
      #   # OrderDecider::PlaceOrder produces: ["orders.order_placed"]
      #
      # @example Inspect automation (reaction) wiring
      #   nodes = CCC::Topology.build([OrderDecider, NotificationDecider])
      #
      #   nodes.select { |n| n.type == 'automation' }.each do |aut|
      #     puts "#{aut.name}: consumes #{aut.consumes} => dispatches #{aut.produces}"
      #   end
      #   # reaction(OrderPlaced): consumes ["orders.order_placed"] => dispatches ["notifications.send_receipt"]
      #
      # @example Projector readmodel wiring
      #   nodes = CCC::Topology.build([OrderSummaryProjector])
      #
      #   rm = nodes.find { |n| n.type == 'readmodel' }
      #   puts "#{rm.name} consumes #{rm.consumes}, triggers #{rm.produces}"
      #   # OrderSummaryProjector consumes ["orders.order_placed"], triggers ["orders.order_placed-OrderSummaryProjector-aut"]
      def self.build(reactors)
        analyzer = Analyzer.new
        nodes = []
        command_ids = {}
        event_nodes = {}

        reactors.each do |reactor|
          group_id = reactor.group_id

          # Command nodes (deciders only)
          if reactor.respond_to?(:handled_commands)
            reactor.handled_commands.each do |cmd_class|
              next if command_ids.key?(cmd_class.type)

              produced_refs = analyzer.events_produced_by(reactor, cmd_class)
              produced_types = resolve_refs(produced_refs, reactor)

              schema = extract_schema(cmd_class)
              cmd_node = CommandNode.new(
                type: 'command',
                id: cmd_class.type,
                name: cmd_class.name,
                group_id: group_id,
                produces: produced_types,
                schema: schema
              )
              nodes << cmd_node
              command_ids[cmd_class.type] = cmd_node

              # Register event nodes discovered via Prism from this command's handler
              produced_types.each do |evt_type|
                next if event_nodes.key?(evt_type)
                next if command_ids.key?(evt_type)

                evt_class = find_event_class(evt_type)
                next unless evt_class

                event_nodes[evt_type] = EventNode.new(
                  type: 'event',
                  id: evt_type,
                  name: evt_class.name,
                  group_id: group_id,
                  produces: [],
                  schema: extract_schema(evt_class)
                )
              end
            end
          end

          # Event nodes from evolve handlers (covers projectors and events not yet seen)
          if reactor.respond_to?(:handled_messages_for_evolve)
            reactor.handled_messages_for_evolve.each do |evt_class|
              # Skip command classes that ended up in evolve handlers
              next if evt_class < CCC::Command

              evt_type = evt_class.type
              next if event_nodes.key?(evt_type)
              next if command_ids.key?(evt_type)

              event_nodes[evt_type] = EventNode.new(
                type: 'event',
                id: evt_type,
                name: evt_class.name,
                group_id: group_id,
                produces: [],
                schema: extract_schema(evt_class)
              )
            end
          end

          is_projector = reactor < CCC::Projector
          rm_id = is_projector ? "#{Sourced::Types::ModuleToMessageType.parse(group_id)}-rm" : nil
          projector_aut_ids = []

          # Automation nodes from reactions
          if reactor.respond_to?(:handled_messages_for_react)
            catch_all_events = reactor.respond_to?(:catch_all_react_events) ? reactor.catch_all_react_events : Set.new
            specific_events = reactor.handled_messages_for_react.reject { |e| catch_all_events.include?(e) }

            # Specific reactions: one automation node per reacted event
            specific_events.each do |evt_class|
              produced_refs = analyzer.commands_dispatched_by(reactor, evt_class)
              produced_types = resolve_refs(produced_refs, reactor)

              aut_id = "#{evt_class.type}-#{group_id}-aut"
              projector_aut_ids << aut_id if is_projector

              nodes << AutomationNode.new(
                type: 'automation',
                id: aut_id,
                name: "reaction(#{evt_class.name})",
                group_id: group_id,
                consumes: is_projector ? [rm_id] : [evt_class.type],
                produces: produced_types
              )
            end

            # Catch-all reaction: single automation node for all catch-all events
            if catch_all_events.any?
              produced_refs = analyzer.commands_dispatched_by(reactor, catch_all_events.first)
              produced_types = resolve_refs(produced_refs, reactor)

              group_type_id = Sourced::Types::ModuleToMessageType.parse(group_id)
              aut_id = "#{group_type_id}-aut"
              projector_aut_ids << aut_id if is_projector

              consumes = if is_projector
                [rm_id]
              else
                catch_all_events.map(&:type)
              end

              nodes << AutomationNode.new(
                type: 'automation',
                id: aut_id,
                name: "reaction(#{group_id})",
                group_id: group_id,
                consumes: consumes,
                produces: produced_types
              )
            end
          end

          # ReadModel nodes (projectors only)
          if is_projector
            consumes = reactor.handled_messages_for_evolve
              .reject { |c| c < CCC::Command }
              .map(&:type)

            nodes << ReadModelNode.new(
              type: 'readmodel',
              id: rm_id,
              name: group_id,
              group_id: group_id,
              consumes: consumes,
              produces: projector_aut_ids,
              schema: {}
            )
          end
        end

        nodes + event_nodes.values
      end

      # Resolve AST references to CCC message type strings.
      #
      # Each reference is a two-element array from the Prism analyzer:
      # - +[:const, "WidgetCreated"]+ — constant reference
      # - +[:symbol, "widget_created"]+ — symbol reference resolved via +reactor[]+
      # - +[:const_path, "MyApp::WidgetCreated"]+ — fully qualified constant
      # - +[:const_index, {receiver: "Reactor", index: "cmd"}]+ — bracket accessor
      #
      # @param refs [Array<Array>] AST reference pairs
      # @param reactor [Class] reactor class for namespace resolution
      # @return [Array<String>] resolved, unique message type strings
      def self.resolve_refs(refs, reactor)
        refs.filter_map do |ref_type, ref_value|
          resolve_ref(ref_type, ref_value, reactor)
        end.uniq
      end

      # Resolve a single AST reference to a message type string.
      #
      # @param ref_type [Symbol] one of +:symbol+, +:const+, +:const_path+, +:const_index+
      # @param ref_value [String, Hash] the reference value from Prism analysis
      # @param reactor [Class] reactor class for namespace resolution
      # @return [String, nil] resolved type string, or +nil+ if unresolvable
      def self.resolve_ref(ref_type, ref_value, reactor)
        case ref_type
        when :symbol
          resolve_symbol_ref(ref_value, reactor)
        when :const
          resolve_const_ref(ref_value, reactor)
        when :const_path
          resolve_const_path_ref(ref_value)
        when :const_index
          resolve_const_index_ref(ref_value, reactor)
        end
      end

      # Resolve a symbol reference (e.g. +:widget_created+) via the reactor's
      # bracket accessor (+reactor[:widget_created]+).
      #
      # @param symbol_name [String] symbol name without colon
      # @param reactor [Class] reactor class responding to +[]+
      # @return [String, nil] type string or +nil+
      def self.resolve_symbol_ref(symbol_name, reactor)
        sym = symbol_name.to_sym
        if reactor.respond_to?(:[])
          begin
            reactor[sym]&.type
          rescue StandardError
            nil
          end
        end
      end

      # Resolve an unqualified constant name by searching the reactor's module
      # hierarchy, then top-level.
      #
      # @param const_name [String] unqualified constant name (e.g. +"WidgetCreated"+)
      # @param reactor [Class] reactor class for namespace context
      # @return [String, nil] type string or +nil+
      def self.resolve_const_ref(const_name, reactor)
        klass = Sourced::Topology.send(:resolve_constant_in_context, const_name, reactor)
        klass&.respond_to?(:type) ? klass.type : nil
      end

      # Resolve a fully qualified constant path (e.g. +"MyApp::WidgetCreated"+).
      #
      # @param path [String] fully qualified constant path
      # @return [String, nil] type string or +nil+
      def self.resolve_const_path_ref(path)
        klass = Object.const_get(path)
        klass.type
      rescue NameError
        nil
      end

      # Resolve a +Reactor[:symbol]+ bracket-accessor reference.
      #
      # @param ref [Hash] with +:receiver+ (constant name) and +:index+ (symbol name)
      # @param reactor [Class] reactor class for namespace resolution
      # @return [String, nil] type string or +nil+
      def self.resolve_const_index_ref(ref, reactor)
        receiver_name = ref[:receiver]
        klass = if receiver_name.include?('::')
                  Object.const_get(receiver_name)
                else
                  Sourced::Topology.send(:resolve_constant_in_context, receiver_name, reactor)
                end
        return nil unless klass && klass.respond_to?(:[])

        klass[ref[:index].to_sym].type
      rescue StandardError
        nil
      end

      # Look up a CCC event class by type string from {CCC::Message.registry}.
      #
      # @param type_string [String] message type (e.g. +"orders.order_placed"+)
      # @return [Class, nil] the event class or +nil+
      def self.find_event_class(type_string)
        CCC::Message.registry[type_string]
      end

      # Extract JSON Schema from a message class's +Payload+ constant.
      #
      # @param msg_class [Class] a {CCC::Message} subclass
      # @return [Hash] JSON Schema hash, or +{}+ if no schema is available
      def self.extract_schema(msg_class)
        return {} unless msg_class.const_defined?(:Payload, false)

        payload_class = msg_class::Payload
        if payload_class.respond_to?(:to_json_schema)
          payload_class.to_json_schema
        else
          {}
        end
      rescue StandardError
        {}
      end

      private_class_method :resolve_refs, :resolve_ref, :resolve_symbol_ref,
                           :resolve_const_ref, :resolve_const_path_ref,
                           :resolve_const_index_ref,
                           :find_event_class, :extract_schema
    end
  end
end
